import type React from "react"
import type { Metadata, Viewport } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import { defaultLocale } from "@/lib/i18n/config"
import iosSplashDevices from "@/lib/ios-splash-devices.json"
import "./globals.css"

// -- iOS launch screens ------------------------------------------------
// Next's Metadata API has no field for apple-touch-startup-image, so we
// render the <link> tags directly. PNGs are generated by `npm run splash`
// from the same device list. env() handles the safe areas at runtime.
const appleSplashLinks = iosSplashDevices.flatMap((d) =>
  (["light", "dark"] as const).map((scheme) => ({
    rel: "apple-touch-startup-image",
    href: `/splash/${d.name}-${scheme}.png`,
    media:
      `(device-width: ${d.w}px) and (device-height: ${d.h}px) ` +
      `and (-webkit-device-pixel-ratio: ${d.dpr}) and (orientation: portrait) ` +
      `and (prefers-color-scheme: ${scheme})`,
  })),
)

// -- Lift typography ---------------------------------------------------
// Geist for everything UI · Geist Mono for tabular data, labels, timers.
// Both exposed as CSS variables so Tailwind v4's @theme inline can wire
// them up as --font-sans / --font-mono in globals.css.
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
  weight: ["400", "500", "600"],
})

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://yeahbuddy.fit"
const isVercelRuntime = process.env.VERCEL === "1"

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "YeahBuddy Fitness — Log the set. Move on.",
    template: "%s | YeahBuddy Fitness",
  },
  description:
    "Track workouts, log meals, monitor weight progress, and connect with professional coaches to achieve your fitness goals. Your all-in-one fitness companion.",
  keywords: [
    "fitness app",
    "workout tracker",
    "meal logging",
    "weight tracking",
    "calorie counter",
    "fitness coach",
    "gym tracker",
    "nutrition tracker",
    "body weight log",
    "exercise tracker",
    "macro tracker",
    "personal trainer",
    "fitness goals",
    "strength training",
  ],
  authors: [{ name: "YeahBuddy Fitness" }],
  creator: "YeahBuddy Fitness",
  publisher: "YeahBuddy Fitness",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: "vi_VN",
    url: siteUrl,
    siteName: "YeahBuddy Fitness",
    title: "YeahBuddy Fitness — Log the set. Move on.",
    description:
      "Track workouts, log meals, monitor weight progress, and connect with professional coaches to achieve your fitness goals.",
    images: [
      {
        url: "/fitness-person.png",
        width: 1200,
        height: 630,
        alt: "YeahBuddy Fitness — Your Fitness Companion",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "YeahBuddy Fitness — Log the set. Move on.",
    description:
      "Track workouts, log meals, monitor weight progress, and connect with professional coaches to achieve your fitness goals.",
    images: ["/fitness-person.png"],
    creator: "@yeahbuddyfit",
  },
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      { url: "/android-icon-192x192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [
      { url: "/apple-icon-57x57.png", sizes: "57x57", type: "image/png" },
      { url: "/apple-icon-60x60.png", sizes: "60x60", type: "image/png" },
      { url: "/apple-icon-72x72.png", sizes: "72x72", type: "image/png" },
      { url: "/apple-icon-76x76.png", sizes: "76x76", type: "image/png" },
      { url: "/apple-icon-114x114.png", sizes: "114x114", type: "image/png" },
      { url: "/apple-icon-120x120.png", sizes: "120x120", type: "image/png" },
      { url: "/apple-icon-144x144.png", sizes: "144x144", type: "image/png" },
      { url: "/apple-icon-152x152.png", sizes: "152x152", type: "image/png" },
      { url: "/apple-icon-180x180.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
  },
  manifest: "/manifest.json",
  category: "health & fitness",
  // Windows tiles (msapplication) — favicon set referenced via browserconfig
  other: {
    "msapplication-TileColor": "#ffffff",
    "msapplication-TileImage": "/ms-icon-144x144.png",
    "msapplication-config": "/browserconfig.xml",
  },
  // -- iOS "Add to Home Screen" — run fullscreen like a native app -----
  appleWebApp: {
    capable: true,
    title: "YeahBuddy",
    statusBarStyle: "default",
  },
}

export const viewport: Viewport = {
  themeColor: "#fcfcfa", // warm paper white — matches --background
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover", // let content extend under the notch; pair with env(safe-area-inset-*)
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={defaultLocale}>
      <head>
        <link rel="dns-prefetch" href="https://bljmubatdtvuomucqmoj.supabase.co" />
        <link rel="preconnect" href="https://bljmubatdtvuomucqmoj.supabase.co" crossOrigin="anonymous" />
        {appleSplashLinks.map((link) => (
          <link key={link.href} rel={link.rel} href={link.href} media={link.media} />
        ))}
      </head>
      <body className={`${geist.variable} ${geistMono.variable} font-sans antialiased`}>
        {children}
        {isVercelRuntime ? <Analytics /> : null}
      </body>
    </html>
  )
}
