export const legalMessages = {
  vi: {
    home: "Về trang chủ", contents: "Nội dung", updated: "Cập nhật ngày 12/09/2026", contact: "Liên hệ và yêu cầu về dữ liệu", contactCopy: "Để hỏi về chính sách, yêu cầu truy cập, chỉnh sửa hoặc xóa dữ liệu, hãy liên hệ đơn vị vận hành YeahBuddy Fitness qua địa chỉ hỗ trợ bên dưới. Chúng tôi có thể yêu cầu xác minh chủ tài khoản trước khi xử lý.", contactPending: "Thông tin liên hệ hỗ trợ đang được cập nhật.",
    privacy: {
      title: "Chính sách quyền riêng tư", description: "Cách YeahBuddy Fitness thu thập, sử dụng và bảo vệ thông tin của bạn.",
      sections: [
        { title: "Phạm vi áp dụng", body: "Chính sách này áp dụng cho YeahBuddy Fitness, ứng dụng quản lý tập luyện, dinh dưỡng và kết nối huấn luyện viên, cùng tính năng kết nối Google Sheets. Bạn có thể đọc chính sách mà không cần đăng nhập." },
        { title: "Thông tin được xử lý", body: "Chúng tôi xử lý thông tin tài khoản và hồ sơ bạn cung cấp, như email, tên, vai trò và mục tiêu; dữ liệu tập luyện, bữa ăn, cân nặng, số đo và tiến độ bạn nhập; nội dung trao đổi với tính năng AI nếu bạn sử dụng. Máy chủ cũng có thể ghi nhận thông tin kỹ thuật như địa chỉ IP, thời điểm yêu cầu và lỗi để vận hành và bảo vệ dịch vụ." },
        { title: "Mục đích sử dụng và chia sẻ", body: "Dữ liệu được dùng để xác thực tài khoản, lưu nhật ký, hiển thị tiến độ, quản lý chương trình và hỗ trợ bạn. Huấn luyện viên được bạn kết nối hoặc được cấp quyền hợp lệ có thể xem dữ liệu học viên phục vụ huấn luyện. Nhà cung cấp hạ tầng, lưu trữ và xác thực xử lý dữ liệu cần thiết để vận hành dịch vụ; quản trị viên có thể truy cập theo trách nhiệm hỗ trợ và bảo mật. Chúng tôi không bán dữ liệu cá nhân. Thông tin có thể được cung cấp khi pháp luật yêu cầu." },
        { title: "Kết nối tài khoản Google", body: "Khi bạn chủ động kết nối Google, ứng dụng nhận email và thông tin nhận diện tài khoản qua openid và userinfo.email; quyền spreadsheets cho phép đọc, tạo và cập nhật bảng tính phục vụ nhập, xuất chương trình tập; drive.file cho phép truy cập các tệp bạn sử dụng với ứng dụng trong phạm vi quyền Google cấp. Quyền spreadsheets có phạm vi rộng hơn một tệp; ứng dụng dùng quyền này cho các thao tác bảng tính bạn yêu cầu. Chúng tôi lưu email Google, phạm vi quyền, thời hạn token và token truy cập/làm mới được mã hóa để duy trì kết nối, kể cả khi bạn không đăng nhập lại Google." },
        { title: "Giới hạn sử dụng dữ liệu Google", body: "Việc sử dụng và chuyển giao thông tin nhận từ Google APIs tuân theo Google API Services User Data Policy, bao gồm yêu cầu Limited Use. Dữ liệu Google chỉ được dùng để cung cấp hoặc cải thiện tính năng mà bạn sử dụng; không dùng cho quảng cáo cá nhân hóa, bán cho bên môi giới dữ liệu hoặc huấn luyện mô hình AI dùng chung. Quyền truy cập của con người được giới hạn theo sự đồng ý của bạn hoặc nhu cầu bảo mật, nghĩa vụ pháp lý và các ngoại lệ được chính sách Google cho phép." },
        { title: "Ngắt kết nối, lưu trữ và xóa dữ liệu", body: "Bạn có thể ngắt kết nối Google trong tính năng kết nối của ứng dụng hoặc thu hồi quyền trong tài khoản Google. Ngắt kết nối trong ứng dụng xóa bản ghi kết nối và token đã lưu, đồng thời gửi yêu cầu thu hồi token tới Google. Chương trình đã nhập vào YeahBuddy và tệp đã xuất sang Google vẫn tồn tại cho đến khi được xóa riêng. Dữ liệu tài khoản được giữ trong thời gian cần thiết để cung cấp dịch vụ; khi có yêu cầu xóa, dữ liệu có thể được giữ lại trong phạm vi cần thiết để tuân thủ pháp luật, giải quyết tranh chấp hoặc bảo mật. Bản sao lưu có thể chưa bị xóa đồng thời với dữ liệu đang hoạt động." },
        { title: "Cookie, lưu trữ trên thiết bị và AI", body: "Ứng dụng sử dụng cookie cho phiên đăng nhập và ngôn ngữ; lưu trữ trên thiết bị cho giao diện và bản nháp buổi tập. Khi triển khai trên Vercel, dịch vụ phân tích truy cập và hiệu năng của Vercel được bật. Khi bạn dùng AI, nội dung yêu cầu và ngữ cảnh cần thiết có thể được gửi tới nhà cung cấp AI được cấu hình để tạo phản hồi. Tránh nhập thông tin nhạy cảm không cần thiết hoặc dữ liệu người khác khi chưa được phép." },
        { title: "Bảo vệ dữ liệu và thay đổi chính sách", body: "Chúng tôi sử dụng kiểm soát truy cập và mã hóa token Google để giảm rủi ro truy cập trái phép. Không hệ thống nào bảo đảm an toàn tuyệt đối. Dữ liệu có thể được xử lý tại quốc gia nơi nhà cung cấp hạ tầng hoạt động. Khi chính sách thay đổi, chúng tôi cập nhật nội dung và ngày sửa đổi trên trang này; những thay đổi cần sự đồng ý sẽ được thông báo hoặc yêu cầu xác nhận phù hợp." },
      ],
    },
    terms: {
      title: "Điều khoản dịch vụ", description: "Quyền và trách nhiệm khi sử dụng YeahBuddy Fitness.",
      sections: [
        { title: "Chấp nhận điều khoản", body: "Khi sử dụng YeahBuddy Fitness, bạn đồng ý với các điều khoản này và đã đọc Chính sách quyền riêng tư. Nếu không đồng ý, hãy ngừng sử dụng dịch vụ. Nếu sử dụng thay cho tổ chức hoặc học viên, bạn phải có quyền thực hiện các thao tác và xử lý dữ liệu tương ứng." },
        { title: "Tài khoản và điều kiện sử dụng", body: "Bạn có trách nhiệm cung cấp thông tin chính xác, bảo vệ thông tin đăng nhập và thông báo khi nghi ngờ tài khoản bị truy cập trái phép. Bạn phải có đủ năng lực đồng ý với điều khoản theo pháp luật áp dụng; nếu cần sự cho phép của người giám hộ, phải có sự cho phép đó trước khi sử dụng." },
        { title: "Phạm vi dịch vụ và sức khỏe", body: "YeahBuddy hỗ trợ ghi nhận tập luyện, dinh dưỡng, tiến độ và làm việc với huấn luyện viên. Nội dung, phép tính và gợi ý AI mang tính tham khảo, có thể có sai sót và không thay thế chẩn đoán, điều trị hoặc tư vấn của chuyên gia y tế. Hãy chọn mức vận động phù hợp với tình trạng của bạn và dừng tập khi xuất hiện dấu hiệu bất thường. Chúng tôi không cam kết một kết quả sức khỏe hoặc thể hình cụ thể." },
        { title: "Nội dung của bạn và trách nhiệm huấn luyện viên", body: "Bạn giữ quyền đối với nội dung mình tạo và cho phép YeahBuddy lưu trữ, xử lý, hiển thị nội dung đó trong phạm vi cần thiết để cung cấp dịch vụ. Bạn phải có quyền sử dụng dữ liệu, bảng tính và tài liệu tải lên. Huấn luyện viên chịu trách nhiệm về nội dung hướng dẫn, quyền truy cập dữ liệu học viên và các thỏa thuận huấn luyện của mình." },
        { title: "Google Sheets và dịch vụ bên thứ ba", body: "Kết nối Google là tùy chọn và chịu phạm vi quyền bạn cấp. Bạn cần kiểm tra bảng tính đích và nội dung trước khi nhập, xuất hoặc cập nhật dữ liệu. Bạn có thể thu hồi kết nối; thao tác này không tự xóa các tệp Google hay chương trình đã nhập. Google, nhà cung cấp AI và các dịch vụ bên thứ ba có điều khoản riêng; gián đoạn hoặc thay đổi từ họ có thể ảnh hưởng đến tính năng." },
        { title: "Hành vi không được phép", body: "Không truy cập tài khoản hay dữ liệu khi chưa được phép; phá hoại, khai thác lỗ hổng hoặc gây quá tải dịch vụ; phát tán mã độc, nội dung bất hợp pháp hay vi phạm quyền riêng tư và sở hữu trí tuệ. Không sử dụng dữ liệu học viên hoặc dữ liệu Google ngoài mục đích và quyền đã được cấp." },
        { title: "Tính sẵn có, phí và chấm dứt", body: "Tính năng có thể được cập nhật, bảo trì hoặc tạm gián đoạn. Nếu cung cấp tính năng trả phí, mức phí và điều kiện thanh toán sẽ được thông báo trước khi bạn mua. Chúng tôi có thể hạn chế hoặc đình chỉ tài khoản để xử lý vi phạm, bảo vệ người dùng hoặc đáp ứng yêu cầu pháp luật. Bạn có thể ngừng sử dụng và yêu cầu xóa dữ liệu theo Chính sách quyền riêng tư." },
        { title: "Trách nhiệm và giải quyết vấn đề", body: "Trong phạm vi pháp luật cho phép, dịch vụ được cung cấp theo tính sẵn có và không bảo đảm luôn liên tục hay hoàn toàn không có lỗi. Không điều khoản nào loại trừ trách nhiệm hoặc quyền của người tiêu dùng mà pháp luật không cho phép loại trừ. Nếu có vấn đề hoặc tranh chấp, hãy liên hệ đơn vị vận hành để tìm cách giải quyết; các quyền khiếu nại và yêu cầu cơ quan có thẩm quyền bảo vệ vẫn được giữ nguyên." },
        { title: "Thay đổi điều khoản", body: "Phiên bản hiện hành được công bố tại trang này cùng ngày cập nhật. Thay đổi quan trọng sẽ được thông báo phù hợp; khi pháp luật yêu cầu, chúng tôi sẽ xin sự đồng ý trước khi áp dụng. Bạn có thể ngừng sử dụng nếu không chấp nhận điều khoản mới." },
      ],
    },
  },
  en: {
    home: "Back to home", contents: "Contents", updated: "Updated September 12, 2026", contact: "Contact and data requests", contactCopy: "For policy questions or requests to access, correct or delete data, contact the operator of YeahBuddy Fitness at the support address below. We may verify account ownership before processing a request.", contactPending: "Support contact details are being updated.",
    privacy: {
      title: "Privacy Policy", description: "How YeahBuddy Fitness collects, uses and protects your information.",
      sections: [
        { title: "Scope", body: "This policy covers YeahBuddy Fitness, its workout, nutrition and coaching features, and its Google Sheets integration. This policy is publicly accessible without signing in." },
        { title: "Information we process", body: "We process account and profile details you provide, such as email, name, role and goals; workout, meal, weight, measurement and progress records; and content you submit to AI features. Servers may also record technical information such as IP addresses, request times and errors to operate and secure the service." },
        { title: "Use and sharing", body: "We use data to authenticate accounts, save records, display progress, manage programs and provide support. Coaches you connect with or who have valid authorization can access trainee information for coaching. Infrastructure, storage and authentication providers process data needed to operate the service; administrators may access it for support and security responsibilities. We do not sell personal data. We may disclose information when legally required." },
        { title: "Google account connection", body: "When you choose to connect Google, openid and userinfo.email identify your account; spreadsheets allows reading, creating and updating spreadsheets for program import and export; drive.file permits access to files you use with the app within Google's grant. The spreadsheets permission is broader than a single file; we use it for spreadsheet operations you request. We store your Google email, granted scopes, token expiry and encrypted access and refresh tokens to maintain the connection without repeated Google sign-in." },
        { title: "Limited Use of Google data", body: "Our use and transfer of information received from Google APIs follows the Google API Services User Data Policy, including Limited Use requirements. Google data is used to provide or improve features you use, not for personalized advertising, sale to data brokers or training general-purpose AI models. Human access is limited to your consent, security needs, legal obligations and exceptions permitted by Google's policy." },
        { title: "Disconnecting, retention and deletion", body: "Disconnect Google in the app or revoke access in your Google account. Disconnecting in the app deletes the stored connection and tokens and attempts to revoke the token with Google. Imported YeahBuddy programs and exported Google files remain until separately deleted. Account data is retained as needed to provide the service; following a deletion request, limited retention may be necessary for legal obligations, disputes or security. Backup copies may not be erased at the same time as active records." },
        { title: "Cookies, device storage and AI", body: "We use cookies for authentication and language, and device storage for preferences and workout drafts. Vercel analytics and performance monitoring are enabled when deployed on Vercel. When you use AI features, your request and necessary context may be sent to the configured AI provider to generate a response. Avoid submitting unnecessary sensitive information or other people's data without permission." },
        { title: "Security and policy updates", body: "Access controls and Google token encryption help reduce unauthorized access. No system can guarantee absolute security. Data may be processed in countries where infrastructure providers operate. We update this page and its revision date when this policy changes, and provide appropriate notice or obtain consent for changes that require it." },
      ],
    },
    terms: {
      title: "Terms of Service", description: "Your rights and responsibilities when using YeahBuddy Fitness.",
      sections: [
        { title: "Acceptance", body: "By using YeahBuddy Fitness, you agree to these terms and acknowledge the Privacy Policy. Stop using the service if you do not agree. If acting for an organization or trainee, you must have authority to perform the relevant actions and process their data." },
        { title: "Accounts and eligibility", body: "Provide accurate information, protect your credentials and report suspected unauthorized access. You must have the legal capacity to accept these terms under applicable law and obtain guardian permission where required before using the service." },
        { title: "Service and health information", body: "YeahBuddy supports workout, nutrition and progress tracking and coaching. Content, calculations and AI suggestions are informational, may contain errors and do not replace medical diagnosis, treatment or professional advice. Choose activities appropriate to your condition and stop exercising if unusual symptoms occur. We do not guarantee particular health or fitness results." },
        { title: "Your content and coaching responsibilities", body: "You retain rights to content you create and permit YeahBuddy to store, process and display it as needed to deliver the service. You must have permission to use uploaded data, spreadsheets and materials. Coaches are responsible for their guidance, access to trainee data and their own coaching agreements." },
        { title: "Google Sheets and third parties", body: "Google connection is optional and operates within your granted permissions. Review the destination spreadsheet and content before importing, exporting or updating records. Revoking the connection does not automatically delete Google files or imported programs. Google, AI providers and other third parties have their own terms; their changes or outages may affect features." },
        { title: "Prohibited conduct", body: "Do not access accounts or data without permission, damage or overload the service, exploit vulnerabilities, distribute malware or unlawful content, or infringe privacy or intellectual property rights. Do not use trainee or Google data beyond authorized purposes and permissions." },
        { title: "Availability, fees and termination", body: "Features may change or be interrupted for maintenance. Any paid features will disclose fees and payment terms before purchase. We may restrict or suspend accounts to address violations, protect users or comply with law. You may stop using the service and request data deletion under the Privacy Policy." },
        { title: "Responsibility and disputes", body: "To the extent permitted by law, the service is provided as available without a guarantee of uninterrupted or error-free operation. These terms do not exclude liability or consumer rights that cannot legally be excluded. Contact the operator to seek resolution of problems or disputes; your right to seek assistance from competent authorities remains unaffected." },
        { title: "Changes to these terms", body: "The current version and revision date appear on this page. Material changes will receive appropriate notice, and consent will be requested where required by law. You may stop using the service if you do not accept updated terms." },
      ],
    },
  },
}
