import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

import type { NutrientAmounts } from "./nutrients"

/**
 * Micronutrients for the system food library, per library serving, keyed by
 * the Vietnamese name in `vietnamese-foods.ts`.
 *
 * Generated by `scripts/import-usda-nutrients.ts` (ingredients) and
 * `scripts/estimate-dish-nutrients.ts` (prepared dishes), committed so the
 * numbers can be reviewed in a diff, and loaded by the food seed.
 */
type FoodNutrientEntry = {
  source: "usda" | "ai"
  /** "fdc:<id> <USDA description>" for USDA rows; the recipe assumption for AI rows. */
  sourceRef: string
  /** The serving weight the amounts were scaled to, so a changed serving is detectable. */
  servingGrams: number
  nutrients: NutrientAmounts
}

type FoodNutrientData = Record<string, FoodNutrientEntry>

const DATA_PATH = join(__dirname, "food-nutrients.data.json")

function readFoodNutrientData(): FoodNutrientData {
  try {
    return JSON.parse(readFileSync(DATA_PATH, "utf8")) as FoodNutrientData
  } catch {
    return {}
  }
}

/** Sorted keys keep regenerated files diffable. */
function writeFoodNutrientData(data: FoodNutrientData) {
  const sorted = Object.fromEntries(Object.entries(data).sort(([left], [right]) => left.localeCompare(right, "vi")))
  writeFileSync(DATA_PATH, `${JSON.stringify(sorted, null, 2)}\n`, "utf8")
}

export { DATA_PATH, readFoodNutrientData, writeFoodNutrientData, type FoodNutrientData, type FoodNutrientEntry }
